name: Auto-tag release

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  actions: read

jobs:
  auto-tag:
    uses: tylerbutler/actions/.github/workflows/auto-tag.yml@77f80621309fc7443b628802e08a815d41dd4b47
    with:
      create-release: true
