name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-hex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6

      - name: Setup Gleam
        uses: tylerbutler/actions/setup-gleam@17116c2d3dfb57c2db7967fcecf0fc878e4cb6cf
        with:
          erlang-version: "27.2"
          gleam-version: "1.16.0"
          run-deps: "false"

      - name: Download dependencies
        run: gleam deps download

      - name: Publish package to Hex
        uses: tylerbutler/actions/gleam-publish@17116c2d3dfb57c2db7967fcecf0fc878e4cb6cf
        with:
          packages: "."
          working-directory: "."
          hex-api-key: ${{ secrets.HEX_API_KEY }}
          skip-already-published: "true"
