name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-hex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6

      - name: Setup Gleam
        uses: tylerbutler/actions/setup-gleam@ee7def5950abcf0a519add705a95719ab345c05e # ratchet:tylerbutler/actions/setup-gleam@v1
        with:
          erlang-version: "27.2"
          gleam-version: "1.16.0"
          run-deps: "false"

      - name: Download dependencies
        run: gleam deps download

      - name: Publish package to Hex
        uses: tylerbutler/actions/gleam-publish@ee7def5950abcf0a519add705a95719ab345c05e # ratchet:tylerbutler/actions/gleam-publish@v1
        with:
          packages: "."
          working-directory: "."
          hex-api-key: ${{ secrets.HEX_API_KEY }}
          skip-already-published: "true"
