name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: ["26.2", "27.2"]
        node: ["20", "22"]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          gleam-version: "1.16.0"
          rebar3-version: "3"
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: gleam deps download
      - run: gleam format --check src test
      - run: gleam test --target erlang
      - run: gleam test --target javascript
      - run: gleam docs build
